version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: citydynamics
      POSTGRES_USER: citydynamics
    volumes:
      - ./deploy/backup-db.sh:/backup-db.sh
      - ./deploy/backup:/backup

  api:
    build: ./api
    ports:
      - "8117:8001"
    links:
      - database:database
    environment:
      - DB_NAME=city-dynamics
      - DB_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8001
      - UWSGI_MODULE=citydynamics.wsgi:application
      - UWSGI_MASTER=1
      - UWSGI_STATIC_MAP=/citydynamics/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_SAFE=static/
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1

  importer:
    build: ./importer
    links:
      - database:database
    environment:
      # Following are secret, should be provided as environment variables.
      # E.g. by running in terminal
      # export EXTERN_DATASERVICES_PASSWORD="mypassword"
      EXTERN_DATASERVICES_PASSWORD:
    volumes:
      - /app/data:/data

  analyzer:
    build: ./analyzer
    links:
      - database:database
