version: "3.0"
services:
  database:
    build: ./database
    ports:
      - "5403:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: citydynamics
      POSTGRES_USER: citydynamics

  web:
    build: ./web
    ports:
      - "8125:8001"
    links:
      - database:database
    environment:
      DB_NAME: citydynamics
      DB_PASSWORD: insecure
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "citydynamics.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/citydynamics/static=/static"

  importer:
    build: ./importer
    links:
      - database:database
    environment:
      # Following are secret, should be provided as environment variables.
      # E.g. by running in terminal
      # export EXTERN_DATASERVICES_PASSWORD="mypassword"
      EXTERN_DATASERVICES_PASSWORD:
    volumes:
      - /app/data:/data

  analyzer:
    build: ./analyzer
    links:
      - database:database
