version: '3.0'
services:

  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: citydynamics
      POSTGRES_USER: citydynamics
    volumes:
      - ./backups:/tmp/backups
      - ./backup-google-current.sh:/backup-google-current.sh
      - ./backup-db-google.sh:/backup-db-google.sh

  importer:
    image: build.datapunt.amsterdam.nl:5000/stadswerken/citydynamics_importer:${ENVIRONMENT}
    # build: ../../
    links:
      - database
    environment:
      DATABASE_NAME: citydynamics
      DATABASE_USER: citydynamics
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      STADSWERKEN_OBJECTSTORE_PASSWORD:
      PYTHONPATH: /app/scrape_quantillion
      QUANTILLION_PASSWORD:
      ENVIRONMENT:
      GOOGLE_DAYS: 50
    command: >
      bash -c "/app/deploy/docker-wait.sh \
              && /app/run_import.sh \ "
    volumes:
      - data-volume:/data
      - ./backups:/backups
      - ./backup-google-current.sh:/backup-google-current.sh

  api:
    image: build.datapunt.amsterdam.nl:5000/stadswerken/citydynamics_api:${ENVIRONMENT}
    links:
      - database:database
    environment:
      - DB_NAME=city-dynamics
      - DB_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8001
      - UWSGI_MODULE=citydynamics.wsgi:application
      - UWSGI_MASTER=1
      - UWSGI_STATIC_MAP=/citydynamics/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_STATIC_INDEX=index.html

  analyzer:
    image: build.datapunt.amsterdam.nl:5000/stadswerken/citydynamics_analyzer:${ENVIRONMENT}
    # build: ./analyzer
    links:
      - database:database

volumes:
  data-volume:
