version: '3.0'
services:

  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: citydynamics
      POSTGRES_USER: citydynamics
    volumes:
      - ./backups:/tmp/backups
      - ./backup-google-current.sh:/backup-google-current.sh
      - ./backup-db-google.sh:/backup-db-google.sh

  importer:
    image: build.app.amsterdam.nl:5000/stadswerken/citydynamics_importer:${ENVIRONMENT}
    # build: ../../
    links:
      - database
    environment:
      DATABASE_NAME: citydynamics
      DATABASE_USER: citydynamics
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      STADSWERKEN_OBJECTSTORE_PASSWORD:
      PYTHONPATH: /app/scrape_quantillion
      QUANTILLION_PASSWORD:
      ENVIRONMENT:
      GOOGLE_DAYS: 50

    volumes:
      - data-volume:/data
      - ./backups:/backups
      - ./backup-google-current.sh:/backup-google-current.sh

  api:
    image: build.app.amsterdam.nl:5000/stadswerken/citydynamics:${ENVIRONMENT}
    links:
      - database:database

  analyzer:
    image: build.app.amsterdam.nl:5000/stadswerken/citydynamics_analyzer:${ENVIRONMENT}
    # build: ./analyzer
    links:
      - database:database

volumes:
  data-volume:
